export const Questions = [
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 4??',
		optionA: '24',
		optionB: '5',
		optionC: '4',
		optionD: '2',
		answer: 'optionB',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
	{
		prompt: 'What is 1 + 3??',
		optionA: '24',
		optionB: '21',
		optionC: '4',
		optionD: '2',
		answer: 'optionC',
	},
];

export const extraQuestion = [
	{
		prompt: 'Who played the role of Sherlock Homes in TV Series??',
		optionA: 'Robert Downey Jr',
		optionB: 'Tony Stark',
		optionC: 'Benedict Cummberbatch',
		optionD: 'None',
		answer: 'optionC',
	},
	{
		prompt: 'Who played the role of Sherlock Homes in Movie??',
		optionA: 'Robert Downey Jr',
		optionB: 'Tony Stark',
		optionC: 'Benedict Cummberbatch',
		optionD: 'None',
		answer: 'optionA',
	},
];
